import { ArtPiece } from '../types';
import { drawGenerativeArt } from './renderEngine';
import { DOWNLOAD_RESOLUTION, SHARE_RESOLUTION } from '../constants';

export const downloadHighRes = (piece: ArtPiece) => {
  const canvas = document.createElement('canvas');
  canvas.width = DOWNLOAD_RESOLUTION;
  canvas.height = DOWNLOAD_RESOLUTION;
  const ctx = canvas.getContext('2d');
  
  if (ctx) {
    drawGenerativeArt(ctx, piece.attributes, piece.seed, DOWNLOAD_RESOLUTION, DOWNLOAD_RESOLUTION);
    const link = document.createElement('a');
    link.download = `Lumina_${piece.title.replace(/\s+/g, '_')}_HighRes.png`;
    link.href = canvas.toDataURL('image/png');
    link.click();
  }
};

export const shareArt = (piece: ArtPiece) => {
  const canvas = document.createElement('canvas');
  canvas.width = SHARE_RESOLUTION;
  canvas.height = SHARE_RESOLUTION;
  const ctx = canvas.getContext('2d');

  if (ctx) {
    drawGenerativeArt(ctx, piece.attributes, piece.seed, SHARE_RESOLUTION, SHARE_RESOLUTION);
    
    canvas.toBlob(async (blob) => {
      if (!blob) return;

      const file = new File([blob], `Lumina_${piece.title.replace(/\s+/g, '_')}.png`, { type: 'image/png' });
      const shareData = {
        title: piece.title,
        text: `"${piece.prompt.substring(0, 100)}..." — Generated by Lumina Gallery`,
        files: [file],
      };

      if (navigator.share && navigator.canShare && navigator.canShare(shareData)) {
        try {
          await navigator.share(shareData);
        } catch (err) {
          // User cancelled
          console.debug("Share cancelled");
        }
      } else {
        const text = encodeURIComponent(`${piece.title}\n\n"${piece.prompt.substring(0, 180)}..."\n\n#GenerativeArt #Lumina`);
        window.open(`https://twitter.com/intent/tweet?text=${text}`, '_blank');
      }
    }, 'image/png');
  }
};